### ISSUE TITLE
Crown Custom Text-Name Hover

### ISSUE THREAD

**Issue by YuukiSystems** [Puyodead1/powercord-ownertag#15]
here we see the normal staff tag with the crown.
![](https://cdn.discordapp.com/attachments/755004260902764646/858757062284541952/unknown.png)

but if you want to customize it. it dont work. and you must disable the crown.

![](https://cdn.discordapp.com/attachments/755004260902764646/858756882465554443/unknown.png)

result: 
![image](https://user-images.githubusercontent.com/41828138/123553790-8fe58680-d77d-11eb-8416-c4d8ad759f3f.png)

can you make it like the default crown, but WITH the custom name. so we can hover over it and see the custom text. like here?

![unknown](https://user-images.githubusercontent.com/41828138/123553946-1b5f1780-d77e-11eb-8b38-42d1318de9f9.png)

that would be awesome! ❤️

**Comment by Puyodead1** [comment]
I'll look into this!

**Comment by Puyodead1** [comment]
After looking, this is a bug. It's suppose to show the custom text but isn't.

**Comment by Puyodead1** [comment]
This should be fixed now (commit b10a3d40468e6c38dfd3032e252df65a68c37c88), just update the plugin.
